
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gspterfjllouqrxvagix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcHRlcmZqbGxvdXFyeHZhZ2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mzc2MTEsImV4cCI6MjA1ODMxMzYxMX0.APljyUgYdS5fq884VC7GqRr7332O0tjXnRnpLWT_658";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
